wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.7
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.7
    start_time: 1672324640.898063
    t:
      1:
      - 1
      - 5
      - 35
      - 53
      - 55
      2:
      - 1
      - 5
      - 35
      - 53
      - 55
      3:
      - 2
      - 13
      - 16
      - 23
      4: 3.9.7
      5: 0.13.7
      8:
      - 3
      - 5
d_inner:
  desc: null
  value: 16
d_time:
  desc: null
  value: 16
d_type_emb:
  desc: null
  value: 8
n_head:
  desc: null
  value: 8
n_layers:
  desc: null
  value: 2
trial.number:
  desc: null
  value: 0
