wandb_version: 1

CIF_config:
  desc: null
  value: {}
DAM_config:
  desc: null
  value: {}
ES_pat:
  desc: null
  value: 100
INPUT:
  desc: null
  value: TE
NOISE_config:
  desc: null
  value: {}
OUTPUT:
  desc: null
  value: none-mark
TE_config:
  desc: null
  value:
    d_inner: 128
    d_k: 32
    d_time: 16
    d_type_emb: 32
    d_v: 32
    dropout: 0.1
    n_head: 4
    n_layers: 4
    n_marks: 200
    time_enc: concat
_wandb:
  desc: null
  value:
    cli_version: 0.13.9
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.7
    start_time: 1676654999.095657
    t:
      1:
      - 1
      - 5
      - 35
      - 53
      - 55
      2:
      - 1
      - 5
      - 35
      - 53
      - 55
      3:
      - 2
      - 3
      - 13
      - 16
      - 23
      4: 3.9.7
      5: 0.13.9
      8:
      - 8
balanced_batch:
  desc: null
  value: true
batch_size:
  desc: null
  value: 32
cuda:
  desc: null
  value: 1
data:
  desc: null
  value: /home/hokarami/data/synthea_200/split0/
data_label:
  desc: null
  value: multilabel
date:
  desc: null
  value: 17-02-23--17-29-50
demo:
  desc: null
  value: false
demo_config:
  desc: null
  value: {}
device:
  desc: null
  value: cuda
epoch:
  desc: null
  value: 11
event_enc:
  desc: null
  value: 1
freeze:
  desc: null
  value: ''
hparams2write:
  desc: null
  value:
    ES_pat: 100
    balanced_batch: true
    batch_size: 32
    cuda: 1
    data: /home/hokarami/data/synthea_200/
    data_label: multilabel
    demo: false
    epoch: 11
    event_enc: 1
    freeze: ''
    int_dec: sahp
    log: log.txt
    log_freq: 10
    lr: 0.003
    mark_detach: 0
    mod: none
    next_mark: 1
    noise: false
    num_states: 1
    per: 10
    pos_alpha: 1.0
    prof: false
    sample_label: 0
    setting: ''
    smooth: 0.0
    split: '0'
    state: false
    te_d_inner: 128
    te_d_k: 32
    te_d_mark: 32
    te_d_rnn: 256
    te_d_time: 16
    te_d_v: 32
    te_dropout: 0.1
    te_n_head: 4
    te_n_layers: 4
    test_center: ''
    time_enc: concat
    transfer_learning: ''
    user_prefix: '[AAR60-TE__nextmark-concat]'
    w_class: false
    w_event: 1.0
    w_pos: true
    w_pos_label: 1.0
    w_sample_label: 10000.0
    w_time: 1.0
    wandb: true
    wandb_project: TEEDAM_unsupervised_timeCat
    weight_decay: 1.0
int_dec:
  desc: null
  value: sahp
label_config:
  desc: null
  value: 0
label_loss_fun:
  desc: null
  value: BCEWithLogitsLoss()
log:
  desc: null
  value: log.txt
log_freq:
  desc: null
  value: 10
lr:
  desc: null
  value: 0.003
mark_detach:
  desc: null
  value: 0
mod:
  desc: null
  value: none
next_mark:
  desc: null
  value: 1
next_time_config:
  desc: null
  value: true
next_type_config:
  desc: null
  value:
    mark_detach: 0
    n_marks: 200
noise:
  desc: null
  value: false
num_demos:
  desc: null
  value: 0
num_marks:
  desc: null
  value: 200
num_states:
  desc: null
  value: 1
num_types:
  desc: null
  value: 200
per:
  desc: null
  value: 10
pos_alpha:
  desc: null
  value: 1.0
pos_weight:
  desc: null
  value: "[ 7.94070231  2.22880023 36.81724363 32.23662457 11.77260093 50.\n 15.85733419\
    \ 17.20583611 50.         14.10203975 50.         50.\n 50.         47.34519038\
    \ 50.         16.83348734 16.83348734 50.\n 50.         50.         11.37669944\
    \ 39.50524696 50.          2.99993091\n 20.37253599 22.70157197 50.         50.\
    \         50.         50.\n 50.         50.         11.2681273  50.         50.\
    \         50.\n 50.         50.         25.42546782 50.         50.         50.\n\
    \ 50.         50.         50.         50.         50.         50.\n 50.      \
    \   50.         49.36377871 50.         50.         50.\n 50.         50.    \
    \     50.         50.         50.         50.\n 50.         50.         50.  \
    \       50.         50.         50.\n 50.         50.         50.         50.\
    \         50.         50.\n 50.         50.         50.         50.         50.\
    \         50.\n 50.         50.         50.         50.         50.         50.\n\
    \ 50.         50.         50.         50.         50.         50.\n  9.67838436\
    \ 50.         50.         16.70912094 15.49991451 50.\n 50.         50.      \
    \   50.         50.         50.         50.\n 50.         50.         50.    \
    \     26.91081759 50.         50.\n 50.         50.         50.         50.  \
    \       50.         50.\n 50.         50.         50.         50.         50.\
    \         16.01087084\n 50.         50.         50.         50.         50.  \
    \       50.\n 50.         19.73866323 19.73866323 50.         50.         50.\n\
    \ 50.         35.59347744 50.         50.         50.         50.\n 50.      \
    \   50.         50.         50.         50.         50.\n 50.         50.    \
    \     50.         50.         50.         50.\n 50.         50.         50.  \
    \       50.         50.         50.\n 50.         40.34404456 50.         50.\
    \         50.         50.\n 50.         50.         50.         50.         50.\
    \         50.\n 50.         50.         50.         13.47816954 50.         50.\n\
    \ 50.         50.         50.         50.         50.         50.\n 50.      \
    \   50.         50.         50.         50.         50.\n 50.         50.    \
    \     50.         50.         50.         50.\n 50.         50.         50.  \
    \       50.         50.         50.\n 50.         50.        ]"
pred_loss_func:
  desc: null
  value: BCEWithLogitsLoss()
prof:
  desc: null
  value: false
run_id:
  desc: null
  value: '1532263'
run_name:
  desc: null
  value: '[AAR60-TE__nextmark-concat]1532263-'
run_path:
  desc: null
  value: /home/hokarami/data/synthea_200/split0/[AAR60-TE__nextmark-concat]1532263-/
sample_label:
  desc: null
  value: 0
setting:
  desc: null
  value: ''
smooth:
  desc: null
  value: 0.0
split:
  desc: null
  value: '0'
state:
  desc: null
  value: false
str_config:
  desc: null
  value: '-'
te_d_inner:
  desc: null
  value: 128
te_d_k:
  desc: null
  value: 32
te_d_mark:
  desc: null
  value: 32
te_d_rnn:
  desc: null
  value: 256
te_d_time:
  desc: null
  value: 16
te_d_v:
  desc: null
  value: 32
te_dropout:
  desc: null
  value: 0.1
te_n_head:
  desc: null
  value: 4
te_n_layers:
  desc: null
  value: 4
test_center:
  desc: null
  value: ''
testloader:
  desc: null
  value: <torch.utils.data.dataloader.DataLoader object at 0x7f60f7e950d0>
time_enc:
  desc: null
  value: concat
trainloader:
  desc: null
  value: <torch.utils.data.dataloader.DataLoader object at 0x7f61b2745e80>
transfer_learning:
  desc: null
  value: ''
type_loss:
  desc: null
  value: Utils.type_loss_BCE
user_prefix:
  desc: null
  value: '[AAR60-TE__nextmark-concat]'
validloader:
  desc: null
  value: <torch.utils.data.dataloader.DataLoader object at 0x7f60f7e951f0>
w:
  desc: null
  value: "[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.\n\
    \ 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.\n 1.\
    \ 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.\n 1. 1.\
    \ 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.\n 1. 1. 1.\
    \ 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.\n 1. 1. 1. 1.\
    \ 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.\n 1. 1. 1. 1. 1.\
    \ 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.\n 1. 1. 1. 1. 1. 1.\
    \ 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.\n 1. 1. 1. 1. 1. 1. 1.\
    \ 1.]"
w_class:
  desc: null
  value: false
w_event:
  desc: null
  value: 1.0
w_pos:
  desc: null
  value: true
w_pos_label:
  desc: null
  value: 1.0
w_sample_label:
  desc: null
  value: 10000.0
w_time:
  desc: null
  value: 1.0
wandb:
  desc: null
  value: true
wandb_project:
  desc: null
  value: TEEDAM_unsupervised_timeCat
weight_decay:
  desc: null
  value: 1.0
