wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.7
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.7
    start_time: 1671622776.840484
    t:
      1:
      - 1
      - 5
      - 35
      - 53
      - 55
      2:
      - 1
      - 5
      - 35
      - 53
      - 55
      3:
      - 13
      - 16
      - 23
      - 35
      4: 3.9.7
      5: 0.13.7
      8:
      - 3
      - 5
balanced_batch:
  desc: null
  value: true
batch_size:
  desc: null
  value: 8
data:
  desc: null
  value: C:/DATA/data/processed/physio2019_1d_HP_std_AB/
data_label:
  desc: null
  value: multilabel
date:
  desc: null
  value: 21-12-22--12-39-34
demo:
  desc: null
  value: false
device:
  desc: null
  value: cpu
epoch:
  desc: null
  value: 15
event_enc:
  desc: null
  value: 1
freeze:
  desc: null
  value: ''
hparams2write:
  desc: null
  value:
    balanced_batch: true
    batch_size: 8
    data: C:/DATA/data/processed/physio2019_1d_HP_std_AB/
    data_label: multilabel
    demo: false
    epoch: 15
    event_enc: 1
    freeze: ''
    int_dec: sahp
    log: log.txt
    lr: 0.00245
    mark_detach: 0
    mod: none
    next_mark: 0
    num_states: 1
    per: 50
    pos_alpha: 1.0
    sample_label: 1
    smooth: 0.0
    state: true
    te_d_inner_hid: 16
    te_d_k: 8
    te_d_mark: 8
    te_d_rnn: 256
    te_d_time: 8
    te_d_v: 8
    te_dropout: 0.1
    te_n_head: 4
    te_n_layers: 4
    time_enc: concat
    transfer_learning: ''
    user_prefix: '[bal8]TEDA__label-'
    w_class: false
    w_event: 1
    w_pos: true
    w_sample_label: 100.0
    w_time: 1.0
    wandb: true
int_dec:
  desc: null
  value: sahp
log:
  desc: null
  value: log.txt
lr:
  desc: null
  value: 0.00245
mark_detach:
  desc: null
  value: 0
mod:
  desc: null
  value: none
next_mark:
  desc: null
  value: 0
num_states:
  desc: null
  value: 1
per:
  desc: null
  value: 50
pos_alpha:
  desc: null
  value: 1.0
run_folder:
  desc: null
  value: C:/DATA/data/processed/physio2019_1d_HP_std_AB/[bal8]TEDA__label-954557-none-state1-per50/
run_id:
  desc: null
  value: '954557'
run_name:
  desc: null
  value: '[bal8]TEDA__label-954557-none-state1-per50'
sample_label:
  desc: null
  value: 1
smooth:
  desc: null
  value: 0.0
state:
  desc: null
  value: true
str_config:
  desc: null
  value: -none-state1-per50
te_d_inner_hid:
  desc: null
  value: 16
te_d_k:
  desc: null
  value: 8
te_d_mark:
  desc: null
  value: 8
te_d_rnn:
  desc: null
  value: 256
te_d_time:
  desc: null
  value: 8
te_d_v:
  desc: null
  value: 8
te_dropout:
  desc: null
  value: 0.1
te_n_head:
  desc: null
  value: 4
te_n_layers:
  desc: null
  value: 4
time_enc:
  desc: null
  value: concat
transfer_learning:
  desc: null
  value: ''
user_prefix:
  desc: null
  value: '[bal8]TEDA__label-'
w_class:
  desc: null
  value: false
w_event:
  desc: null
  value: 1
w_pos:
  desc: null
  value: true
w_sample_label:
  desc: null
  value: 100.0
w_time:
  desc: null
  value: 1.0
wandb:
  desc: null
  value: true
